import React from "react";
import "../globals.css";
import { inter, roboto, poppins, montserrat } from "../lib/fonts";

import GoogleOneTap from "@/src/components/client-components/googleAuth/GoogleOneTap";
import { getSession } from "../lib/authentication";
import NavBar from "@/src/components/server-components/Navbar/NavBar";
import AppContextProvider from "../_contextApi/AppContext";
import ModelContextProvider from "../_contextApi/ModelContextApi";
import AuthContextProvider from "../_contextApi/authContext";
import TagContextProvider from "../_contextApi/TagContextApi";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { GOOGLE_AUTH_CLIENT_ID } from "@/config";
import Footer from "@/src/components/server-components/footer/Footer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({ children }) {
  const userDetails = await getSession();
  return (
    <html
      lang="en"
      className={`${inter.variable} ${roboto.variable} ${poppins.variable} ${montserrat.variable}`}
    >
      <body>
        <AppContextProvider>
          <ModelContextProvider>
            <AuthContextProvider authData={userDetails}>
              <TagContextProvider>
                <GoogleOAuthProvider clientId={GOOGLE_AUTH_CLIENT_ID}>
                  <div>
                    <NavBar userData={userDetails} />
                    {!userDetails && <GoogleOneTap />}
                  </div>
                  <div className="children_wrapper">
                    {children}

                    <div>
                      <Footer />
                    </div>
                  </div>
                </GoogleOAuthProvider>
              </TagContextProvider>
            </AuthContextProvider>
          </ModelContextProvider>
        </AppContextProvider>
      </body>
    </html>
  );
}
